# Generated by Django 4.1.5 on 2023-01-17 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_voucher',
            name='financial_year_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.financial_year'),
        ),
        migrations.AlterField(
            model_name='account_voucher',
            name='voucher_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.voucher_type'),
        ),
    ]
